# Generated by Django 4.1.5 on 2023-02-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_password1_member_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('writer', models.CharField(max_length=20)),
                ('brief', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=6)),
                ('link_photo', models.CharField(max_length=100)),
            ],
        ),
    ]
