# Generated by Django 4.1.5 on 2023-02-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_book_name_alter_book_price_alter_book_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_pages',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='brief',
            field=models.TextField(null=True),
        ),
    ]
