# Generated by Django 4.1.5 on 2023-02-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_book_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.AddField(
            model_name='book',
            name='link_download',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
